-- SET SESSION SQL_MODE = 'TRADITIONAL,ANSI,ANSI_QUOTES';
SELECT CONCAT(
    'ALTER TABLE "', TABLE_NAME, '" ', 'ADD ',
        IF(NON_UNIQUE = 1,
            CASE UPPER( INDEX_TYPE )
                WHEN 'FULLTEXT' THEN 'FULLTEXT INDEX'
                WHEN 'SPATIAL' THEN 'SPATIAL INDEX'
                ELSE CONCAT( 'INDEX "', INDEX_NAME, '" USING ', INDEX_TYPE )
            END,
            IF( UPPER( INDEX_NAME ) = 'PRIMARY',
                CONCAT( 'PRIMARY KEY USING ', INDEX_TYPE ),
                CONCAT( 'UNIQUE INDEX "', INDEX_NAME, '" USING ', INDEX_TYPE )
            )
        ),
    '(',
    GROUP_CONCAT( DISTINCT CONCAT( '"', COLUMN_NAME, '"' ) ORDER BY SEQ_IN_INDEX ASC SEPARATOR ', ' ),
    ');'
) AS 'SQL_CODE'
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = ?
GROUP BY TABLE_NAME, INDEX_NAME;
