SET SESSION SQL_MODE = 'ANSI,TRADITIONAL,ANSI_QUOTES';
SELECT TABLE_SCHEMA AS "SCHEMA"
     , TABLE_NAME AS "TABLE"
     , ENGINE AS "ENGINE"
     , CASE
           WHEN DATA_LENGTH >= 1024*1024*1024 THEN LPAD( CONCAT( ROUND( DATA_LENGTH /1024/1024/1024, 2 ), ' GB' ), 10, SPACE(1) )
           WHEN DATA_LENGTH >= 1024*1024      THEN LPAD( CONCAT( ROUND( DATA_LENGTH /1024/1024     , 2 ), ' MB' ), 10, SPACE(1) )
           WHEN DATA_LENGTH >= 1024           THEN LPAD( CONCAT( ROUND( DATA_LENGTH /1024          , 2 ), ' KB' ), 10, SPACE(1) )
           ELSE                                      LPAD( CONCAT( ROUND( DATA_LENGTH              , 2 ), '  B' ), 10, SPACE(1) )
       END AS "DATA SIZE"
     , CASE
           WHEN INDEX_LENGTH >= 1024*1024*1024 THEN LPAD( CONCAT( ROUND( INDEX_LENGTH /1024/1024/1024, 2 ), ' GB' ), 10, SPACE(1) )
           WHEN INDEX_LENGTH >= 1024*1024      THEN LPAD( CONCAT( ROUND( INDEX_LENGTH /1024/1024     , 2 ), ' MB' ), 10, SPACE(1) )
           WHEN INDEX_LENGTH >= 1024           THEN LPAD( CONCAT( ROUND( INDEX_LENGTH /1024          , 2 ), ' KB' ), 10, SPACE(1) )
           ELSE                                       LPAD( CONCAT( ROUND( INDEX_LENGTH              , 2 ), '  B' ), 10, SPACE(1) )
       END AS "INDEX SIZE"
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA NOT IN ( 'information_schema', 'mysql' )
ORDER BY DATA_LENGTH, INDEX_LENGTH;
